# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from obstacle_detector/Boundingbox_array.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import obstacle_detector.msg

class Boundingbox_array(genpy.Message):
  _md5sum = "72f4806878af1954f3e5c66182495641"
  _type = "obstacle_detector/Boundingbox_array"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Boundingbox[] boundingbox_array

================================================================================
MSG: obstacle_detector/Boundingbox
float64 x
float64 y
float64 z
float64 volume
float64 distance
"""
  __slots__ = ['boundingbox_array']
  _slot_types = ['obstacle_detector/Boundingbox[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       boundingbox_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Boundingbox_array, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.boundingbox_array is None:
        self.boundingbox_array = []
    else:
      self.boundingbox_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.boundingbox_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundingbox_array:
        _x = val1
        buff.write(_get_struct_5d().pack(_x.x, _x.y, _x.z, _x.volume, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.boundingbox_array is None:
        self.boundingbox_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundingbox_array = []
      for i in range(0, length):
        val1 = obstacle_detector.msg.Boundingbox()
        _x = val1
        start = end
        end += 40
        (_x.x, _x.y, _x.z, _x.volume, _x.distance,) = _get_struct_5d().unpack(str[start:end])
        self.boundingbox_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.boundingbox_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundingbox_array:
        _x = val1
        buff.write(_get_struct_5d().pack(_x.x, _x.y, _x.z, _x.volume, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.boundingbox_array is None:
        self.boundingbox_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundingbox_array = []
      for i in range(0, length):
        val1 = obstacle_detector.msg.Boundingbox()
        _x = val1
        start = end
        end += 40
        (_x.x, _x.y, _x.z, _x.volume, _x.distance,) = _get_struct_5d().unpack(str[start:end])
        self.boundingbox_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
