(cl:defpackage cam_lidar_calibration-msg
  (:use )
  (:export
   "<RUNOPTIMISEACTION>"
   "RUNOPTIMISEACTION"
   "<RUNOPTIMISEACTIONFEEDBACK>"
   "RUNOPTIMISEACTIONFEEDBACK"
   "<RUNOPTIMISEACTIONGOAL>"
   "RUNOPTIMISEACTIONGOAL"
   "<RUNOPTIMISEACTIONRESULT>"
   "RUNOPTIMISEACTIONRESULT"
   "<RUNOPTIMISEFEEDBACK>"
   "RUNOPTIMISEFEEDBACK"
   "<RUNOPTIMISEGOAL>"
   "RUNOPTIMISEGOAL"
   "<RUNOPTIMISERESULT>"
   "RUNOPTIMISERESULT"
  ))

