; Auto-generated. Do not edit!


(cl:in-package cam_lidar_calibration-msg)


;//! \htmlinclude RunOptimiseFeedback.msg.html

(cl:defclass <RunOptimiseFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunOptimiseFeedback (<RunOptimiseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunOptimiseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunOptimiseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cam_lidar_calibration-msg:<RunOptimiseFeedback> is deprecated: use cam_lidar_calibration-msg:RunOptimiseFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunOptimiseFeedback>) ostream)
  "Serializes a message object of type '<RunOptimiseFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunOptimiseFeedback>) istream)
  "Deserializes a message object of type '<RunOptimiseFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunOptimiseFeedback>)))
  "Returns string type for a message object of type '<RunOptimiseFeedback>"
  "cam_lidar_calibration/RunOptimiseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunOptimiseFeedback)))
  "Returns string type for a message object of type 'RunOptimiseFeedback"
  "cam_lidar_calibration/RunOptimiseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunOptimiseFeedback>)))
  "Returns md5sum for a message object of type '<RunOptimiseFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunOptimiseFeedback)))
  "Returns md5sum for a message object of type 'RunOptimiseFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunOptimiseFeedback>)))
  "Returns full string definition for message of type '<RunOptimiseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunOptimiseFeedback)))
  "Returns full string definition for message of type 'RunOptimiseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunOptimiseFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunOptimiseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RunOptimiseFeedback
))
