; Auto-generated. Do not edit!


(cl:in-package cam_lidar_calibration-msg)


;//! \htmlinclude RunOptimiseResult.msg.html

(cl:defclass <RunOptimiseResult> (roslisp-msg-protocol:ros-message)
  ((transform
    :reader transform
    :initarg :transform
    :type geometry_msgs-msg:Transform
    :initform (cl:make-instance 'geometry_msgs-msg:Transform)))
)

(cl:defclass RunOptimiseResult (<RunOptimiseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunOptimiseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunOptimiseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cam_lidar_calibration-msg:<RunOptimiseResult> is deprecated: use cam_lidar_calibration-msg:RunOptimiseResult instead.")))

(cl:ensure-generic-function 'transform-val :lambda-list '(m))
(cl:defmethod transform-val ((m <RunOptimiseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cam_lidar_calibration-msg:transform-val is deprecated.  Use cam_lidar_calibration-msg:transform instead.")
  (transform m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunOptimiseResult>) ostream)
  "Serializes a message object of type '<RunOptimiseResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'transform) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunOptimiseResult>) istream)
  "Deserializes a message object of type '<RunOptimiseResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'transform) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunOptimiseResult>)))
  "Returns string type for a message object of type '<RunOptimiseResult>"
  "cam_lidar_calibration/RunOptimiseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunOptimiseResult)))
  "Returns string type for a message object of type 'RunOptimiseResult"
  "cam_lidar_calibration/RunOptimiseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunOptimiseResult>)))
  "Returns md5sum for a message object of type '<RunOptimiseResult>"
  "c2d1de03cf5b052350d875b7cfbc84a5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunOptimiseResult)))
  "Returns md5sum for a message object of type 'RunOptimiseResult"
  "c2d1de03cf5b052350d875b7cfbc84a5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunOptimiseResult>)))
  "Returns full string definition for message of type '<RunOptimiseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%geometry_msgs/Transform transform~%~%================================================================================~%MSG: geometry_msgs/Transform~%# This represents the transform between two coordinate frames in free space.~%~%Vector3 translation~%Quaternion rotation~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunOptimiseResult)))
  "Returns full string definition for message of type 'RunOptimiseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%geometry_msgs/Transform transform~%~%================================================================================~%MSG: geometry_msgs/Transform~%# This represents the transform between two coordinate frames in free space.~%~%Vector3 translation~%Quaternion rotation~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunOptimiseResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'transform))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunOptimiseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RunOptimiseResult
    (cl:cons ':transform (transform msg))
))
