; Auto-generated. Do not edit!


(cl:in-package cam_lidar_calibration-msg)


;//! \htmlinclude RunOptimiseGoal.msg.html

(cl:defclass <RunOptimiseGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunOptimiseGoal (<RunOptimiseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunOptimiseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunOptimiseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cam_lidar_calibration-msg:<RunOptimiseGoal> is deprecated: use cam_lidar_calibration-msg:RunOptimiseGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunOptimiseGoal>) ostream)
  "Serializes a message object of type '<RunOptimiseGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunOptimiseGoal>) istream)
  "Deserializes a message object of type '<RunOptimiseGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunOptimiseGoal>)))
  "Returns string type for a message object of type '<RunOptimiseGoal>"
  "cam_lidar_calibration/RunOptimiseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunOptimiseGoal)))
  "Returns string type for a message object of type 'RunOptimiseGoal"
  "cam_lidar_calibration/RunOptimiseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunOptimiseGoal>)))
  "Returns md5sum for a message object of type '<RunOptimiseGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunOptimiseGoal)))
  "Returns md5sum for a message object of type 'RunOptimiseGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunOptimiseGoal>)))
  "Returns full string definition for message of type '<RunOptimiseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunOptimiseGoal)))
  "Returns full string definition for message of type 'RunOptimiseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunOptimiseGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunOptimiseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RunOptimiseGoal
))
