(cl:defpackage lidar_team_morai-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<CTRLSTEERING>"
   "CTRLSTEERING"
   "<CTRLVELOCITY>"
   "CTRLVELOCITY"
   "<OBJECTINFO>"
   "OBJECTINFO"
   "<PUREPURSUIT>"
   "PUREPURSUIT"
   "<VESCSTATE>"
   "VESCSTATE"
   "<VESCSTATESTAMPED>"
   "VESCSTATESTAMPED"
   "<WAYPOINT>"
   "WAYPOINT"
  ))

