(cl:in-package pure_pursuit-msg)
(cl:export '(IS_DYNAMIC_OBS_DETECTED_SHORT-VAL
          IS_DYNAMIC_OBS_DETECTED_SHORT
          IS_DYNAMIC_OBS_DETECTED_LONG-VAL
          IS_DYNAMIC_OBS_DETECTED_LONG
))